package NewLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Attribute_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Body_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new BodyElement_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Head_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new HeadElement_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Html_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Text_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L), MetaIdFactory.conceptId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d81f8L), MetaIdFactory.conceptId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d642aL), MetaIdFactory.conceptId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87622b0L), MetaIdFactory.conceptId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87630abL), MetaIdFactory.conceptId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d8c09L), MetaIdFactory.conceptId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb878a167L)).seal();
}
