package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAttribute = createDescriptorForAttribute();
  /*package*/ final ConceptDescriptor myConceptBody = createDescriptorForBody();
  /*package*/ final ConceptDescriptor myConceptBodyElement = createDescriptorForBodyElement();
  /*package*/ final ConceptDescriptor myConceptHead = createDescriptorForHead();
  /*package*/ final ConceptDescriptor myConceptHeadElement = createDescriptorForHeadElement();
  /*package*/ final ConceptDescriptor myConceptHtml = createDescriptorForHtml();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  /*package*/ final EnumerationDescriptor myEnumerationBodyElementNames = new EnumerationDescriptor_BodyElementNames();
  /*package*/ final EnumerationDescriptor myEnumerationHeadElementNames = new EnumerationDescriptor_HeadElementNames();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAttribute, myConceptBody, myConceptBodyElement, myConceptHead, myConceptHeadElement, myConceptHtml, myConceptText);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Attribute:
        return myConceptAttribute;
      case LanguageConceptSwitch.Body:
        return myConceptBody;
      case LanguageConceptSwitch.BodyElement:
        return myConceptBodyElement;
      case LanguageConceptSwitch.Head:
        return myConceptHead;
      case LanguageConceptSwitch.HeadElement:
        return myConceptHeadElement;
      case LanguageConceptSwitch.Html:
        return myConceptHtml;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationBodyElementNames, myEnumerationHeadElementNames);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Attribute", 0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1e740840-f958-4498-af6e-15ae83af88ab(NewLanguage.structure)/2680354325043967349");
    b.version(3);
    b.property("value", 0x2532880eb86d7c7aL).type(PrimitiveTypeId.STRING).origin("2680354325043969146").done();
    b.aggregate("attribute", 0x2532880eb874f260L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L).optional(true).ordered(true).multiple(false).origin("2680354325044458080").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Body", 0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d81f8L);
    b.class_(false, false, false);
    b.origin("r:1e740840-f958-4498-af6e-15ae83af88ab(NewLanguage.structure)/2680354325043970552");
    b.version(3);
    b.aggregate("content", 0x2532880eb86d86d9L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d642aL).optional(true).ordered(true).multiple(true).origin("2680354325043971801").done();
    b.aggregate("text", 0x2532880eb87ba5e5L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb878a167L).optional(true).ordered(true).multiple(false).origin("2680354325044897253").done();
    b.aggregate("attribute", 0x2532880eb875ce4fL).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L).optional(true).ordered(true).multiple(false).origin("2680354325044514383").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBodyElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "BodyElement", 0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d642aL);
    b.class_(false, false, false);
    b.origin("r:1e740840-f958-4498-af6e-15ae83af88ab(NewLanguage.structure)/2680354325044080323");
    b.version(3);
    b.property("name", 0x2532880eb86f2a7bL).type(MetaIdFactory.dataTypeId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86f2428L)).origin("2680354325044079227").done();
    b.aggregate("content", 0x2532880eb86d6bcaL).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d642aL).optional(true).ordered(true).multiple(true).origin("2680354325043964874").done();
    b.aggregate("text", 0x2532880eb87bb492L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb878a167L).optional(true).ordered(true).multiple(false).origin("2680354325044901010").done();
    b.aggregate("attribute", 0x2532880eb86d71caL).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L).optional(true).ordered(true).multiple(false).origin("2680354325043966410").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHead() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Head", 0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87622b0L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1e740840-f958-4498-af6e-15ae83af88ab(NewLanguage.structure)/2680354325044535984");
    b.version(3);
    b.aggregate("content", 0x2532880eb8764b12L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87630abL).optional(true).ordered(true).multiple(true).origin("2680354325044546322").done();
    b.aggregate("text", 0x2532880eb8906e09L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb878a167L).optional(true).ordered(true).multiple(false).origin("2680354325046259209").done();
    b.alias("<");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHeadElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "HeadElement", 0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87630abL);
    b.class_(false, false, false);
    b.origin("r:1e740840-f958-4498-af6e-15ae83af88ab(NewLanguage.structure)/2680354325044539563");
    b.version(3);
    b.property("name", 0x2532880eb876433cL).type(MetaIdFactory.dataTypeId(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb8763fa0L)).origin("2680354325044544316").done();
    b.aggregate("content", 0x2532880eb8763a54L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87630abL).optional(true).ordered(true).multiple(true).origin("2680354325044542036").done();
    b.aggregate("attribute", 0x2532880eb877bb7cL).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L).optional(true).ordered(true).multiple(false).origin("2680354325044640636").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHtml() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Html", 0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d8c09L);
    b.class_(false, false, true);
    b.origin("r:1e740840-f958-4498-af6e-15ae83af88ab(NewLanguage.structure)/2680354325043973129");
    b.version(3);
    b.aggregate("head", 0x2532880eb876268cL).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87622b0L).optional(true).ordered(true).multiple(false).origin("2680354325044536972").done();
    b.aggregate("body", 0x2532880eb86d8e46L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d81f8L).optional(true).ordered(true).multiple(false).origin("2680354325043973702").done();
    b.aggregate("htmlAttribute", 0x2532880eb8756594L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L).optional(true).ordered(true).multiple(false).origin("2680354325044487572").done();
    b.aggregate("bodyAttribute", 0x2532880eb875eb14L).target(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L).optional(true).ordered(true).multiple(false).origin("2680354325044521748").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Text", 0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb878a167L);
    b.class_(false, false, false);
    b.origin("r:1e740840-f958-4498-af6e-15ae83af88ab(NewLanguage.structure)/2680354325044699495");
    b.version(3);
    b.property("text", 0x2532880eb878a3a4L).type(PrimitiveTypeId.STRING).origin("2680354325044700068").done();
    return b.create();
  }
}
