package HTML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_HeadElementNames extends EnumerationDescriptorBase {

  public EnumerationDescriptor_HeadElementNames() {
    super(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb8763fa0L, "HeadElementNames", "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044543392");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_title_0 = new EnumerationDescriptor.MemberDescriptor("title", "title", 0x2532880eb8763fa1L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044543393");
  private final EnumerationDescriptor.MemberDescriptor myMember_meta_0 = new EnumerationDescriptor.MemberDescriptor("meta", "meta", 0x2532880eb8764142L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044543810");
  private final EnumerationDescriptor.MemberDescriptor myMember_style_0 = new EnumerationDescriptor.MemberDescriptor("style", "style", 0x2532880eb8789e76L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044698742");
  private final EnumerationDescriptor.MemberDescriptor myMember_link_0 = new EnumerationDescriptor.MemberDescriptor("link", "link", 0x2532880eb8789f4bL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044698955");
  private final EnumerationDescriptor.MemberDescriptor myMember_script_0 = new EnumerationDescriptor.MemberDescriptor("script", "script", 0x2532880eb8789f84L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044699012");
  private final EnumerationDescriptor.MemberDescriptor myMember_base_0 = new EnumerationDescriptor.MemberDescriptor("base", "base", 0x2532880eb878a05bL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044699227");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb8763fa0L, 0x2532880eb8763fa1L, 0x2532880eb8764142L, 0x2532880eb8789e76L, 0x2532880eb8789f4bL, 0x2532880eb8789f84L, 0x2532880eb878a05bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_title_0, myMember_meta_0, myMember_style_0, myMember_link_0, myMember_script_0, myMember_base_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "title":
        return myMember_title_0;
      case "meta":
        return myMember_meta_0;
      case "style":
        return myMember_style_0;
      case "link":
        return myMember_link_0;
      case "script":
        return myMember_script_0;
      case "base":
        return myMember_base_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
