package HTML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_BodyElementNames extends EnumerationDescriptorBase {

  public EnumerationDescriptor_BodyElementNames() {
    super(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86f2428L, "BodyElementNames", "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044077608");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_div_0 = new EnumerationDescriptor.MemberDescriptor("div", "div", 0x2532880eb86f2429L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044077609");
  private final EnumerationDescriptor.MemberDescriptor myMember_span_0 = new EnumerationDescriptor.MemberDescriptor("span", "span", 0x2532880eb86f25b0L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044078000");
  private final EnumerationDescriptor.MemberDescriptor myMember_p_0 = new EnumerationDescriptor.MemberDescriptor("p", "p", 0x2532880eb876223fL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044535871");
  private final EnumerationDescriptor.MemberDescriptor myMember_h1_0 = new EnumerationDescriptor.MemberDescriptor("h1", "h1", 0x2532880eb8762243L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044535875");
  private final EnumerationDescriptor.MemberDescriptor myMember_h2_0 = new EnumerationDescriptor.MemberDescriptor("h2", "h2", 0x2532880eb8762249L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044535881");
  private final EnumerationDescriptor.MemberDescriptor myMember_h3_0 = new EnumerationDescriptor.MemberDescriptor("h3", "h3", 0x2532880eb876224fL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044535887");
  private final EnumerationDescriptor.MemberDescriptor myMember_h4_0 = new EnumerationDescriptor.MemberDescriptor("h4", "h4", 0x2532880eb8762256L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044535894");
  private final EnumerationDescriptor.MemberDescriptor myMember_h5_0 = new EnumerationDescriptor.MemberDescriptor("h5", "h5", 0x2532880eb876225eL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044535902");
  private final EnumerationDescriptor.MemberDescriptor myMember_h6_0 = new EnumerationDescriptor.MemberDescriptor("h6", "h6", 0x2532880eb8762267L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044535911");
  private final EnumerationDescriptor.MemberDescriptor myMember_pre_0 = new EnumerationDescriptor.MemberDescriptor("pre", "pre", 0x2532880eb8780f35L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044662069");
  private final EnumerationDescriptor.MemberDescriptor myMember_b_0 = new EnumerationDescriptor.MemberDescriptor("b", "b", 0x2532880eb87812d1L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044662993");
  private final EnumerationDescriptor.MemberDescriptor myMember_strong_0 = new EnumerationDescriptor.MemberDescriptor("strong", "strong", 0x2532880eb87812f7L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663031");
  private final EnumerationDescriptor.MemberDescriptor myMember_i_0 = new EnumerationDescriptor.MemberDescriptor("i", "i", 0x2532880eb878136cL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663148");
  private final EnumerationDescriptor.MemberDescriptor myMember_em_0 = new EnumerationDescriptor.MemberDescriptor("em", "em", 0x2532880eb87813aeL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663214");
  private final EnumerationDescriptor.MemberDescriptor myMember_mark_0 = new EnumerationDescriptor.MemberDescriptor("mark", "mark", 0x2532880eb87813f1L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663281");
  private final EnumerationDescriptor.MemberDescriptor myMember_small_0 = new EnumerationDescriptor.MemberDescriptor("small", "small", 0x2532880eb878144fL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663375");
  private final EnumerationDescriptor.MemberDescriptor myMember_del_0 = new EnumerationDescriptor.MemberDescriptor("del", "del", 0x2532880eb8781494L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663444");
  private final EnumerationDescriptor.MemberDescriptor myMember_ins_0 = new EnumerationDescriptor.MemberDescriptor("ins", "ins", 0x2532880eb87814daL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663514");
  private final EnumerationDescriptor.MemberDescriptor myMember_sub_0 = new EnumerationDescriptor.MemberDescriptor("sub", "sub", 0x2532880eb878153bL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663611");
  private final EnumerationDescriptor.MemberDescriptor myMember_sup_0 = new EnumerationDescriptor.MemberDescriptor("sup", "sup", 0x2532880eb878159dL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663709");
  private final EnumerationDescriptor.MemberDescriptor myMember_q_0 = new EnumerationDescriptor.MemberDescriptor("q", "q", 0x2532880eb87816adL, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325044663981");
  private final EnumerationDescriptor.MemberDescriptor myMember_a_0 = new EnumerationDescriptor.MemberDescriptor("a", "a", 0x2532880eb8bb12c7L, "r:1e740840-f958-4498-af6e-15ae83af88ab(HTML.structure)/2680354325049053895");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86f2428L, 0x2532880eb86f2429L, 0x2532880eb86f25b0L, 0x2532880eb876223fL, 0x2532880eb8762243L, 0x2532880eb8762249L, 0x2532880eb876224fL, 0x2532880eb8762256L, 0x2532880eb876225eL, 0x2532880eb8762267L, 0x2532880eb8780f35L, 0x2532880eb87812d1L, 0x2532880eb87812f7L, 0x2532880eb878136cL, 0x2532880eb87813aeL, 0x2532880eb87813f1L, 0x2532880eb878144fL, 0x2532880eb8781494L, 0x2532880eb87814daL, 0x2532880eb878153bL, 0x2532880eb878159dL, 0x2532880eb87816adL, 0x2532880eb8bb12c7L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_div_0, myMember_span_0, myMember_p_0, myMember_h1_0, myMember_h2_0, myMember_h3_0, myMember_h4_0, myMember_h5_0, myMember_h6_0, myMember_pre_0, myMember_b_0, myMember_strong_0, myMember_i_0, myMember_em_0, myMember_mark_0, myMember_small_0, myMember_del_0, myMember_ins_0, myMember_sub_0, myMember_sup_0, myMember_q_0, myMember_a_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "div":
        return myMember_div_0;
      case "span":
        return myMember_span_0;
      case "p":
        return myMember_p_0;
      case "h1":
        return myMember_h1_0;
      case "h2":
        return myMember_h2_0;
      case "h3":
        return myMember_h3_0;
      case "h4":
        return myMember_h4_0;
      case "h5":
        return myMember_h5_0;
      case "h6":
        return myMember_h6_0;
      case "pre":
        return myMember_pre_0;
      case "b":
        return myMember_b_0;
      case "strong":
        return myMember_strong_0;
      case "i":
        return myMember_i_0;
      case "em":
        return myMember_em_0;
      case "mark":
        return myMember_mark_0;
      case "small":
        return myMember_small_0;
      case "del":
        return myMember_del_0;
      case "ins":
        return myMember_ins_0;
      case "sub":
        return myMember_sub_0;
      case "sup":
        return myMember_sup_0;
      case "q":
        return myMember_q_0;
      case "a":
        return myMember_a_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
