package HTML.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public abstract class ElementCreator {
  public static void byElement(SNode node, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<!DOCTYPE html>\n");
    if (SLinkOperations.getTarget(node, LINKS.htmlAttribute$8_Is) == null) {
      tgs.append("<html>\n");
    } else {
      tgs.append("<html");
      ElementCreator.createAttribute(SLinkOperations.getTarget(node, LINKS.htmlAttribute$8_Is), ctx);
      tgs.append(">\n");
    }

    tgs.append("\t<head>\n");
    if (SLinkOperations.getTarget(node, LINKS.head$1Ymr) != null) {
      if (SLinkOperations.getChildren(SLinkOperations.getTarget(node, LINKS.head$1Ymr), LINKS.content$b1cZ) != null) {
        int i = 2;
        for (SNode headElement : SLinkOperations.getChildren(SLinkOperations.getTarget(node, LINKS.head$1Ymr), LINKS.content$b1cZ)) {
          ElementCreator.createHeadElement(headElement, i, ctx);
        }
      }
    }
    tgs.append("\t</head>\n");

    if (SLinkOperations.getTarget(node, LINKS.body$CMYy) != null && SLinkOperations.getTarget(node, LINKS.bodyAttribute$uZAA) != null) {
      tgs.append("<body");
      ElementCreator.createAttribute(SLinkOperations.getTarget(node, LINKS.bodyAttribute$uZAA), ctx);
      tgs.append(">\n");
    } else {
      tgs.append("<body>\n");
    }
    if (SLinkOperations.getTarget(node, LINKS.body$CMYy) != null && SLinkOperations.getChildren(SLinkOperations.getTarget(node, LINKS.body$CMYy), LINKS.content$7Mu7) != null) {
      int i = 1;
      for (SNode bodyElement : SLinkOperations.getChildren(SLinkOperations.getTarget(node, LINKS.body$CMYy), LINKS.content$7Mu7)) {
        ElementCreator.createBodyElement(bodyElement, i, ctx);
      }
    }
    tgs.append("</body>\n");

    tgs.append("</html>");
  }
  protected static void createAttribute(SNode attribute, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(" ");
    tgs.append(SPropertyOperations.getString(attribute, PROPS.name$MnvL).replace("\"", "&quot;"));
    tgs.append("=\"");
    tgs.append(SPropertyOperations.getString(attribute, PROPS.value$aX4U).replace("\"", "&quot;"));
    tgs.append("\"");
    if (SLinkOperations.getTarget(attribute, LINKS.attribute$oIXP) != null) {
      ElementCreator.createAttribute(SLinkOperations.getTarget(attribute, LINKS.attribute$oIXP), ctx);
    }
  }
  protected static void createHeadElement(SNode headElement, int tabs, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("\t".repeat(tabs));
    tgs.append("<");
    tgs.append(SPropertyOperations.getEnum(headElement, PROPS.name$Y86d).toString().replace("\"", "&quot;"));
    if (SLinkOperations.getTarget(headElement, LINKS.attribute$cnGL) != null) {
      ElementCreator.createAttribute(SLinkOperations.getTarget(headElement, LINKS.attribute$cnGL), ctx);
    }
    tgs.append(">\n");
    if (SLinkOperations.getChildren(headElement, LINKS.content$pnaa) != null) {
      int i = tabs + 1;
      for (SNode headElementRec : SLinkOperations.getChildren(headElement, LINKS.content$pnaa)) {
        ElementCreator.createHeadElement(headElementRec, i, ctx);
        i++;
      }
    }
    tgs.append("\t".repeat(tabs));
    tgs.append("</");
    tgs.append(SPropertyOperations.getEnum(headElement, PROPS.name$Y86d).toString().replace("\"", "&quot;"));
    tgs.append(">\n");
  }
  protected static void createBodyElement(SNode bodyElement, int tabs, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("\t".repeat(tabs));
    tgs.append("<");
    tgs.append(SPropertyOperations.getEnum(bodyElement, PROPS.name$dlq3).toString());
    if (SLinkOperations.getTarget(bodyElement, LINKS.attribute$W_qn) != null) {
      ElementCreator.createAttribute(SLinkOperations.getTarget(bodyElement, LINKS.attribute$W_qn), ctx);
    }
    tgs.append(">\n");
    if (SLinkOperations.getChildren(bodyElement, LINKS.content$KWMr) != null) {
      int i = tabs + 1;
      for (SNode bodyElementRec : SLinkOperations.getChildren(bodyElement, LINKS.content$KWMr)) {
        ElementCreator.createBodyElement(bodyElementRec, i, ctx);
        i++;
      }
    }
    tgs.append("\t".repeat(tabs));
    tgs.append("</");
    tgs.append(SPropertyOperations.getEnum(bodyElement, PROPS.name$dlq3).toString().replace("\"", "&quot;"));
    tgs.append(">\n");

  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink htmlAttribute$8_Is = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d8c09L, 0x2532880eb8756594L, "htmlAttribute");
    /*package*/ static final SContainmentLink head$1Ymr = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d8c09L, 0x2532880eb876268cL, "head");
    /*package*/ static final SContainmentLink content$b1cZ = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87622b0L, 0x2532880eb8764b12L, "content");
    /*package*/ static final SContainmentLink bodyAttribute$uZAA = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d8c09L, 0x2532880eb875eb14L, "bodyAttribute");
    /*package*/ static final SContainmentLink body$CMYy = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d8c09L, 0x2532880eb86d8e46L, "body");
    /*package*/ static final SContainmentLink content$7Mu7 = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d81f8L, 0x2532880eb86d86d9L, "content");
    /*package*/ static final SContainmentLink attribute$oIXP = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L, 0x2532880eb874f260L, "attribute");
    /*package*/ static final SContainmentLink attribute$cnGL = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87630abL, 0x2532880eb877bb7cL, "attribute");
    /*package*/ static final SContainmentLink content$pnaa = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87630abL, 0x2532880eb8763a54L, "content");
    /*package*/ static final SContainmentLink attribute$W_qn = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d642aL, 0x2532880eb86d71caL, "attribute");
    /*package*/ static final SContainmentLink content$KWMr = MetaAdapterFactory.getContainmentLink(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d642aL, 0x2532880eb86d6bcaL, "content");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty value$aX4U = MetaAdapterFactory.getProperty(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d7575L, 0x2532880eb86d7c7aL, "value");
    /*package*/ static final SProperty name$Y86d = MetaAdapterFactory.getProperty(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb87630abL, 0x2532880eb876433cL, "name");
    /*package*/ static final SProperty name$dlq3 = MetaAdapterFactory.getProperty(0x6b97a825706c4630L, 0x9e0f315c0b91cdb2L, 0x2532880eb86d642aL, 0x2532880eb86f2a7bL, "name");
  }
}
